signintech/gopdf

image_obj.go

To prevent crash and "too much files open"

Close open image before build

---

content_obj.go
gopdf.go

Reference : [8.4.3.6 Line Dash Pattern](http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf)
Usage:
```
pdf.SetLineType("dashed")
pdf.Line(50, 200, 550, 200)
pdf.SetLineType("dotted")
pdf.Line(50, 400, 550, 400)
```

Add function SetLineType

---

gopdf.go

Most readers seem to be OK with the 'startx' stuff missing, but others (e.g cups-pdf) do not.

Completed the trailer section of the PDF output.

---

gopdf.go

I have added `GoPdf.Read()` and `GoPdf.Close()` to implement `io.Reader` and `io.Closer` interfaces.
The API of existing methods has been kept untouched.

implement io.Reader

---

content_obj.go

All content streams are now compressed (/FlateDecode), which in the
general case should lead to smaller PDF-files.
TODO: maybe make this the default, with the option to turn the
compression off.

Compress content streams

---

cache_content_text.go
current.go
font_option.go
gopdf.go
procset_obj.go
subset_font_obj.go
ttf_option.go

New `Style` field to `TTFOption` wich adds ability to load many fonts with same family name but different styles
ie: Regular, Bold, Italic, Bold|Italic
One of the goals is to make support for HTML element (custom or maybe builtin) that can have text with bold/italic tags

Add support to load fonts with same family name but different styles

---

fontmaker/core/ttfparser.go
image_obj_parse.go

* bytes.Equal in the standard lib does the
same thing as (t *TTFParser) CompareBytes()
* fix spelling of cacheFontData
in ./fontmaker/core/ttfparser.go

Use bytes.Equal(), remove CompareBytes()

---

gopdf.go

Changes signature of WritePdf to return the result of WriteFile so errors can be processed properly

Improve WritePdf to return error from WriteFile

---

cache_content_line.go

when use gopdf to draw some lines to make up a "table", the result PDF seems OK,
but if use some tools (in my OS, use Chrome Browser, in other people, use Adobe Reader) to Print to Physical Printer, it would go to lines crossed.
*You can see attached photo:

When Draw Line, No Need Close Path, so use S NOT s

---

page_sizes.go

Better readable pagesize definition
pdf.Start(gopdf.Config{PageSize: gopdf.PageSizeA4})
I found it tedious defining the pagesizes by hand, and also tried to figure why you had floating for a4, maybe you could elaborate?
Also let me know if you feel this would be better placed elsewhere.
Cheers

Added pagesizes as readable variables

---

gopdf.go

There were several requests for text wrapping, so I created a Cell method that supports multiple lines.
example
```
pdf.MultiCell(&gopdf.Rect{W: 80, H: 50}, "Hello gopdf! Add multiple lines Cell method with auto text wrapping")
```

 Add multiple lines Cell method with auto text wrapping

---

subset_font_obj.go

I noticed certain characters were missing when using a custom font and tracked it down to the test for the EndCharCode in the GroupingTables not including the character. This caused a 'not found glyph' error.
Example showing missing characters (note variations of 'Z'):
Example showing characters included after fix:

Fix boundary error in TTF handling

---

catalog_obj.go
gopdf.go
outlines_obj.go

See https://github.com/signintech/gopdf/issues/47
Note that this add very basic support for outlines. I have added a method AddOutline that adds a bookmark with the specified title to the current page (the very first type of "destination" described at 12.3.2.2 / page 366 in https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf)
`
[ page /XYZ left top zoom ]
`
constrained to left=null top=null and zoom=null.

Add basic support for PDF outlines

---

gopdf.go
gopdf_test.go

Adding a method to retrieve the number of pages already created at the PDF object, including constructing the number of pages object to be calculated
When we creating pages with the PDF, there're times that we need information for the number of pages already created at the PDF, either for some calculations or something else. This pull-request is intended to fulfill that.
I've run the test successfully at local with the result: `ok  	github.com/signintech/gopdf	0.405s`
Originally I intended to use `indexOfPagesObj` attribute, but it cannot be used (it will always return 1).  
Thus, I'm resorting to an additional attribute to be used as the number of pages' definition that will be increased when `AddPage` or `AddPageWithOption` executed.

[Feature] Add number of pages retrieval

---

gopdf.go

Fixes #207 
This PR adds some random binary characters in the file header generation for ISO 32000-1 compliance as mentioned in https://github.com/signintech/gopdf/issues/207#issue-1086421272.

Add random binary characters in file header generation for ISO 32000-1 compliance

---

break_option.go
gopdf.go
gopdf_test.go

To have a higher level of flexibiliity and reduce repetitive code SplitTextWithOption is now the underlying text splitting implementation for SplitText and SplitTextWithWordWrap. Splitting can now be performed individually based on language or font specifics. Two break modes are now available to process texts either with a strict break (allowing mid-word breaks) or with an identifier-sensitive mode (avoiding mid-word breaks). See the code documentation of BreakOption for more info.
Hey @oneplus1000 & @renjunok, I refactored the code in order to be as flexible as possible for different language "restrictions" and text splitting. Since the previous PR (https://github.com/signintech/gopdf/pull/216) got merged a bit too quickly I couldn't update it before it went to master.
Feel free to …

Introduce SplitTextWithOption to allow configurable text splitting.

---

README.md
cache_content_color_cmyk.go
content_obj.go
gopdf.go

New methods were added to keep the library backward compatible with previous versions.

Add possibility to use CMYK color mode for fill and stroke

---

README.md
cache_contact_color_rgb.go
cache_content_color_cmyk.go
cache_content_text.go
cache_content_text_color_cmyk.go
cache_content_text_color_rgb.go
content_obj.go
current.go
gopdf.go
gopdf_test.go
i_cache_color_text.go

1. Added support of CMYK color model for text. In the future it can be easily extended to support more color models.
2. Adjusted naming to be more consistent

Add CMYK color model support for text

---

gopdf.go

The MultiCell method doesn't respect unit that is set at initialization.
```
pdf := gopdf.GoPdf{}
pdf.Start(gopdf.Config{PageSize: *gopdf.PageSizeA4, Unit: gopdf.UnitCM})
```
So here is the fix.

Fix MultiCell metohd

---

gopdf.go

Solves the issue in #214 and fixes my own problem of not being able to load images with transparency from memory easily.

change jpeg to png to support transparency values

---

list_cache_content.go

This PR fixes an issue when changing font configuration in the middle of a text added to a PDF.
Before:
After:
Another example from https://github.com/signintech/gopdf/issues/149 :
Before:
After:

Fixing spacing between different text cache box

---

README.md
gopdf.go
gopdf_test.go

Add support for header and footer functions 
Usage:
```go
pdf.AddHeader(func() {                                                                                                                                                                                                                    
pdf.SetY(5)                                                                                                                                                                                                                           
pdf.Cell(nil, "header")                                                                                                                                                                                                               
}) …
```

add support, test, and documentation for header and footer functions

---

cache_content_custom_line_type.go
content_obj.go
gopdf.go

add support for line types with a custom dash array and phase.
Usage:
pdf.SetCustomLineType([]float64{0.8, 0.8}, 0)
pdf.Line(50, 200, 550, 200)

add support for custom line types beyond dashed and dotted

---

cache_content_text.go
content_obj.go
current.go
gopdf.go

This allows setting the (inter-)character spacing for the current font using `pdf.SetCharSpacing(charSpacingInPt)`.
I tried to implement this as complete as possible and it works for my use case, but I am missing the detailed insight into this library to judge whether there is something missing. Feedback very much appreciated!

feat: add support for character spacing

---

gopdf.go

When reading the docs looking for a way of streaming the PDF as an HTTP response I actually skipped over the `Write(io.Reader) error` function because the name made me think it was an implementation of the `io.Writer` interface.
But it is not and its behavior actually is the behavior described by the `io.WriterTo` interface.
So I thought it was worth submitting this PR that basically renames the `Write` function to `WriteTo` changing its signature slightly to match the `io.WriterTo` interface.
The main goal here is to make the code easier to use for new comers by using a more canonical name for this function.
In order to keep retro-compatibility the old `Writer` method was not deleted but I've added a deprecation note.
It was also necessary to change the countingWriter.offset variable …

Add a `WriteTo` method that implements the `io.WriterTo` interface

---

cache_content_text.go
gopdf.go

Hello.
First of all, thank you (and all contributors) for this fine library.
While I was working with `SplitTextWithOption` I noticed that the method creates a new error instead of returning a defined one. This way of creating errors doesn't allow for an idiomatic error comparison (using `errors.Is` for example). So I defined and exported a few errors that users could potentially want to check. 
There is still room for improvement in error handling in other files, but that would require breaking changes.

Export some errors

---

fontmaker/core/fontmaker.go

When running the go vet linter on the entire project, we encounter a failure stating that an integer to string conversion using "string(c)" can lead to unexpected results. Such a failure might become an error in future versions of Go. See for example https://go.dev/doc/go1.15#vet.
By explicitly converting the integer to a rune before casting it to a string, we avoid this issue and can run go test without the "-vet=off" flag.

Fix go vet failure

---

gopdf.go
page_option.go

- Applied concise return for `isEmpty()`.
- Simplified range for `SetCustomLineType()`.

Remove unnecessary returns

---

fontmaker/core/ttfparser.go
fontmaker/core/ttfparser_cmap_other_format.go
fontmaker/core/ttfparser_kern.go

- Add error checks to skipped returns.
- Replace `os.SEEK_CUR` with `io.SeekCurrent`.

fontmaker: Add error checks

---

cell_option.go
gopdf.go
test/pagination/page_test.go

Implements https://github.com/signintech/gopdf/issues/295. Allows customizing line breaks in the `MultiCell` function.
See `TestLineBreak` in `test/pagination/page_test.go` for an example of usage.

feat: MultiCell custom linebreaking

---

README.md
config.go
examples/mask-image/example.go
examples/mask-with-rotated-image/example.go
fontsizefloat64_test.go
gopdf_test.go
kern_test.go
placeholder_test.go

Resolves Question about A4 paper size https://github.com/signintech/gopdf/issues/129
This follows the sizes outline in https://communities.efi.com/s/article/International-standard-paper-sizes-in-PostScript-and-PDF?language=en_US and replaces uses of the floating point example with the nearest integer variable constant in `page_sizes.go`.

fix: use page size constant as standard for A4

---

gopdf.go

in function MultiCellWithOption,
```
text, err = gp.curr.FontISubset.AddChars(text)
```
This will replace '\n' with ' ' (space), which means it cannot be split by '\n'.
Change the variable `text` to `itext` to get the line height, so that `text` also includes '\n', allowing for proper splitting.

fix can't split text by '\n' in MultiCellWithOption

---

gopdf.go
gopdf_test.go
table.go

1. Add `ImportPagesFromSource` to import all pages from existing pdf file, source can be a file path, byte slice, or (*)io.ReadSeeker.
``` go
pdf.ImportPagesFromSource("./examples/outline_example/outline_demo.pdf", "/MediaBox")
```
2. Fix the table border corners 
to
3. Add `SetPage` to let people can manually change the current page, convenient for quickly inserting content at a specified location
```go
pdf.SetPage(2) // Select page
pdf.SetXY(350, 50)
pdf.Cell(&Rect{W: 20, H: 30}, "Hello World")
```

Import all pages from existing pdf file, Fix table border corners and Set current page method

---

gopdf.go
table_test.go

Hello,this PR was proposed to achieve vertical centering of the Table alignment. For this purpose, the code was slightly modified, "lineHeight" in the code was discarded, and "rectangle.H" was used as the height of the cell-rectangle, but the final implementation effect was what I wanted.
Here is the effect achieved：

Fix: Table with text vertically centered

---

subset_font_obj.go

Hi. This simple PR should help to reduce memory allocations in AddChars()  function.
My test case:
before
```
BenchmarkGenerateDocument-16    30    38637542 ns/op    23502649 B/op    320497 allocs/op
```
after
```
BenchmarkGenerateDocument-16    31    34976746 ns/op    18924331 B/op    205436 allocs/op
```

refactor: reduce memory allocations in AddChars()

---

config.go

- Change multiplication to division for unit conversion
- This fixes the incorrect conversion logic in the PointsToUnits function

fix(config): correct points to units conversion

---

table.go
table_test.go

Tables in gopdf currently do not have the ability to be styled on an individual cell basis in a row.
Example use case: I wanna color the 6th column in the 2nd row in red (you can imagine some conditional logic).
This PR will maintain backwards compatibility as it does not break any APIs.

Add ability to style individual row cells

---

table.go
table_test.go

I wanna pass around the table in my code and having it non-exported is a major hindrance to clean code so making a table interface and having the struct implement it.

Add table interface and few nits

---

gopdf.go

This PR introduces two new functions: pdf.GetStreamPageSizes and pdf.GetPageSizes. They are used to expose the fpdi.GetPageSizes() function so one can get page sizes from existing pdf documents. 
Let me know if you want any changes to this functions

feat: expose page size from fpdi either from a readseeker or from a file

---

cache_color_space.go
color_space_obj.go
content_obj.go
current.go
gopdf.go
procset_obj.go

add new ColorSpace in RGB, with name CutContour because plotter machine use as for cut
`AddColorSpaceRGB("CutContour", 0, 255, 0)`
same in CMYK
`AddColorSpaceCMYK("CutContour", 0, 100, 0, 0)`
than use set function to apply it
`SetColorSpace("CutContour")`

Add ColorSpace implementation for cut contour purposes
