content_obj.go
gopdf.go

Now we can add a colored text.
For example...
```
text := "Red color text"
r := 255
g := 0
b := 0
pdf.Cell(nil, text, r,g,b)
```

Add r,g,b option to pdf.Cell

---

README.md

Modify the import package so as to pass the compile

Update import package

---

content_obj.go
gopdf.go

Make compression of content streams configurable

---

gopdf.go

Add getRoot function to DeviceRGBObj

---

gopdf.go

I just took a quick look at this PR to make sure the bot has done its job of correctly fixing incorrect doc comments without introducing any false positives.
I think we can safely say that the bot has done it's job  :smile:.
If this service is useful to you, please let me know
Note: I've only updated functions that I *know* CodeLingo can rewrite nicely, but you can install it [from the GitHub marketplace](https://github.com/apps/codelingo) to review your PRs automatically and find all issues.

Fix function comments based on best practices from Effective Go

---

gopdf.go
image_obj_parse.go

This commit rewrites some if-else-if-else chains as a switch.
Based on Go style guide:
https://golang.org/doc/effective_go.html#switch
Found by https://go-critic.github.io/overview#ifElseChain-ref

Rewrite if-else-if-else to switch statements

---

cache_contact_color.go
cache_content_text.go

unable to set it back to black 😎
```
if !(r == 0 && g == 0 && b == 0) {
```

fix confusing rgb color set 🤨

---

cache_content_imported_object.go
content_obj.go
gopdf.go
imported_obj.go
procset_obj.go

Add ability to import existing PDFs into GoPDF document.  Integrates with phpdave11/gofpdi free PDF document importer.

Add ability to import existing PDFs into GoPDF document.

---

README.md

Updated README.md because it is not adapted changes in 81ad21f .

Fix incorrect examples due to change in 81ad21f

---

go.mod
go.sum
gopdf.go

Also bumped version of gofpdi to support this feature

Added ability to import page using a stream

---

gopdf.go

Split text into multiple lines based on width
texts, _ = pdf.SplitText("乙方在甲方的合作银行开立乙方自己的电子账户，并将押金1万元存入该账户（须签订甲方、乙方、甲方合作银行电子版三方协议，三方协议约定", 480)
for _, text := range texts {
_ = pdf.Cell(nil, text)
pdfLineHeight += 24
pdf.SetY(pdfLineHeight)
}

add Split text into multiple lines based on width function

---

cache_content_text.go
cid_font_obj.go
config.go
content_obj.go
current.go
debug/debug.go
debug/debug_ch.go
debug/debug_th.go
embedfont_obj.go
encoding_obj.go
ext_g_state_obj.go
font_obj.go
fontconverthelper.go
fontdescriptor_obj.go
gopdf.go
ifont.go
image_obj.go
kern_test.go
margin.go
page_sizes.go
pdf_dictionary_obj.go
procset_obj.go
rect.go
subset_font_obj.go

Code was not linting properly with `golint` and contained multiple typos and missing documentation.
This pull request fixes (some) of these. There are still comments in Thai that should be rewritten in English (I am not a native English speaker too, but still think it's best practice).

Code cleanup

---

cell_option.go

also, changed the comment for the var a little to match the variable

add AllBorders Parameter

---

gopdf.go

add ImageFrom method

---

cache_content_text.go
content_obj.go
current.go
fontsizefloat64_test.go
gopdf.go
strhelper.go

Fixed the bug that would have been introduced by  #191

Update font size from int to float64 (Nr.2)

---

README.md

Adding minimum golang version

---

gopdf.go

I found that the method with attributes was missing when drawing multiline text，so I added a func named MultiCellWithOption.Can you take a look?

add func MultiCellWithOption

---

gopdf.go
page_sizes.go

I need to create A4 landscape, so i create a new page size.

add new page size for A4 landscape

---

README.md
examples/mask-image/example.go
examples/mask-with-rotated-image/example.go
examples/outline_example/outline.go
fontmaker/core/fontmaker.go
fontmaker/main.go
go.mod
image_obj_parse.go
pdf_dictionary_obj.go
subfont_descriptor_obj.go
subset_font_obj.go
test/pagination/page_image_test.go
test/pagination/page_test.go

Error occurs when we are trying to load an image with big dimensions (> 32768 px)

fix parse big image dimensions

---

gopdf.go

I'm trying to create a way to draw text with customizations on each edge: left, right, top, bottom.
In the current version of gopdf there is no way to know the minimum height that any element needs to have to contain a text.
So I thought to include this functionality in the project.

Introducing MeasureCellHeightByText

---

gopdf.go
pdf_info_obj.go

New method will be useful for testing in programs that use the GoPdf.

Add `GetInfo` method and update comments

---

gopdf.go

Adds support for initializing gopdf with an existing instance of gofpdi

Allow initializing gopdf with an existing instance of gofpdi

---

config.go

- Included Pixels (unit & conversion).
- Useful for creating pdf from images.

Add unit & conversion for pixels

---

page_sizes.go

- Support for A3 Landscape Page Size Format.

feat: Support A3 Page Size Format

---

annot_obj.go
gopdf.go
page_obj.go

This fixes #316 and therefore also the main problem in https://github.com/digitorus/pdfsign/issues/50

fix: Annots object not an indirect reference
